### ISSUE TITLE
incompatibility on python12

### ISSUE THREAD

**Issue by michel-io** [city96/ComfyUI-GGUF#158] opened 2024-11-17 00:22 UTC
running with --directml acceleration first got this error:

F:\ComfyUI\custom_nodes\ComfyUI-GGUF-main\nodes.py:79: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:212.)
  torch_tensor = torch.from_numpy(tensor.data) # mmap

those i fix, but then an error where says that tensors are read only...

please fix

**Comment by city96** [comment] 2024-11-27 03:15
Is it possible that this is an issue specific to pytorch nightly (2.6.X) and not python 3.12? I did a quick test but at least on that specific env I can't reproduce it with torch 2.4.0

**Comment by michel-io** [comment] 2024-11-29 20:29
![image](https://github.com/user-attachments/assets/ba050612-f3ba-4e8a-88b6-d2bbfaef91aa)

that is the prompt for the error

**Comment by city96** [comment] 2024-12-03 23:56
What's the actual error? The "UserWarning" line should only be a warning, not a hard error, and in the screenshot above it looks like it still continues with loading the model (which will happen the first time it's used, so there may be some delay there - check disk usage to see if it's loading from disk).

**Comment by michel-io** [comment] 2024-12-07 14:17
first i got this

`Using directml with device:
Total VRAM 1024 MB, total RAM 16304 MB
pytorch version: 2.4.1+cpu
Set vram state to: NORMAL_VRAM
Device: privateuseone
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[Prompt Server] web root: F:\ComfyUI\web

Import times for custom nodes:
   0.0 seconds: F:\ComfyUI\custom_nodes\websocket_image_save.py
   0.1 seconds: F:\ComfyUI\custom_nodes\ComfyUI-GGUF

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Using split attention in VAE
Using split attention in VAE
!!! Exception during processing !!! `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 347, in load_clip
    return (self.load_patcher([clip_path], clip_type, self.load_data([clip_path])),)
  File "F:\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 316, in load_data
    sd = gguf_clip_loader(p)
  File "F:\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 122, in gguf_clip_loader
    raw_sd = gguf_sd_loader(path)
  File "F:\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 39, in gguf_sd_loader
    reader = gguf.GGUFReader(path)
  File "C:\Python310\lib\site-packages\gguf\gguf_reader.py", line 94, in __init__
    if self._get(offs, np.uint32, override_order = '<')[0] != GGUF_MAGIC:
  File "C:\Python310\lib\site-packages\gguf\gguf_reader.py", line 151, in _get
    .newbyteorder(override_order or self.byte_order)
AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

Prompt executed in 7.21 seconds
`

after i manually fix this then got the warning, then the error

**Comment by city96** [comment] 2024-12-07 20:06
The numpy 2.0 issue is known: https://github.com/city96/ComfyUI-GGUF/issues/7 - that's why requirements.txt specifies [numpy<2.0](https://github.com/city96/ComfyUI-GGUF/blob/851564739d166b888dd9cea80f90dc8219393b52/requirements.txt#L2)

**Comment by michel-io** [comment] 2024-12-14 11:48
i'm getting the error on a numpy 2.2 installation

**Comment by city96** [comment] 2024-12-14 15:31
Any 2.X version will have the same error until the upstream fix to llama.cpp's gguf-py is merged.

For now the only two solutions are downgrading to Numpy 1.X or applying the fix outlined in the linked issue above to gguf-py yourself.

Anyway, closing for now as the numpy part is a duplicate of that one, and Python 3.12 does work as far as I can tell.

**Closed by city96** 2024-12-14 15:31 UTC
