### ISSUE TITLE
`newbyteorder` was removed from the ndarray class in NumPy 2.0

### ISSUE THREAD

**Issue by fabiomb** [city96/ComfyUI-GGUF#153] opened 2024-11-04 14:53 UTC
With the new version 0.2.7 i got this error:

"`newbyteorder` was removed from the ndarray class in NumPy 2.0 `arr.view(arr.dtype.newbyteorder(order))` instead."

error log:

# ComfyUI Error Report
## Error Details
- **Node Type:** UnetLoaderGGUF
- **Exception Type:** AttributeError
- **Exception Message:** `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
## Stack Trace
```
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 258, in load_unet
    sd = gguf_sd_loader(unet_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 39, in gguf_sd_loader
    reader = gguf.GGUFReader(path)
             ^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 94, in __init__
    if self._get(offs, np.uint32, override_order = '<')[0] != GGUF_MAGIC:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 151, in _get
    .newbyteorder(override_order or self.byte_order)
     ^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.7
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 6441926656
  - **VRAM Free:** 154114552
  - **Torch VRAM Total:** 5100273664
  - **Torch VRAM Free:** 55925240

## Logs
```
2024-11-04 11:45:29,066 - root - INFO - Total VRAM 6144 MB, total RAM 40180 MB
2024-11-04 11:45:29,067 - root - INFO - pytorch version: 2.5.1+cu124
2024-11-04 11:45:29,068 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-04 11:45:29,068 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
2024-11-04 11:45:30,143 - root - INFO - Using pytorch cross attention
2024-11-04 11:45:31,477 - root - INFO - [Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
2024-11-04 11:45:32,883 - root - WARNING - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\__init__.py", line 1, in <module>
    from .pulidflux import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 11, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

2024-11-04 11:45:32,884 - root - WARNING - Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced module for custom nodes: No module named 'insightface'
2024-11-04 11:45:32,911 - root - INFO - 
Import times for custom nodes:
2024-11-04 11:45:32,911 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-04 11:45:32,911 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-11-04 11:45:32,911 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-11-04 11:45:32,911 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-04 11:45:32,911 - root - INFO -    0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-04 11:45:32,911 - root - INFO -    0.6 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-04 11:45:32,911 - root - INFO - 
2024-11-04 11:45:32,916 - root - INFO - Starting server

2024-11-04 11:45:32,917 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-04 11:50:19,484 - root - INFO - got prompt
2024-11-04 11:50:19,524 - root - INFO - Using pytorch attention in VAE
2024-11-04 11:50:19,525 - root - INFO - Using pytorch attention in VAE
2024-11-04 11:50:20,115 - root - INFO - Requested to load FluxClipModel_
2024-11-04 11:50:20,116 - root - INFO - Loading 1 new model
2024-11-04 11:50:24,607 - root - INFO - loaded completely 0.0 4778.66552734375 True
2024-11-04 11:50:26,101 - root - INFO - Unloading models for lowram load.
2024-11-04 11:50:27,977 - root - INFO - 1 models unloaded.
2024-11-04 11:50:27,977 - root - INFO - Loading 1 new model
2024-11-04 11:50:28,997 - root - INFO - loaded completely 0.0 4778.66552734375 True
2024-11-04 11:50:30,075 - root - ERROR - !!! Exception during processing !!! `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
2024-11-04 11:50:30,078 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 258, in load_unet
    sd = gguf_sd_loader(unet_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 39, in gguf_sd_loader
    reader = gguf.GGUFReader(path)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 94, in __init__
    if self._get(offs, np.uint32, override_order = '<')[0] != GGUF_MAGIC:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\gguf\gguf_reader.py", line 151, in _get
    .newbyteorder(override_order or self.byte_order)
     ^^^^^^^^^^^^
AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

2024-11-04 11:50:30,079 - root - INFO - Prompt executed in 10.59 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":42,"last_link_id":61,"nodes":[{"id":33,"type":"CLIPTextEncode","pos":{"0":390,"1":400},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{"collapsed":true},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":60,"slot_index":0}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[55],"slot_index":0}],"title":"CLIP Text Encode (Negative Prompt)","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""],"color":"#322","bgcolor":"#533"},{"id":8,"type":"VAEDecode","pos":{"0":1151,"1":195},"size":{"0":210,"1":46},"flags":{},"order":9,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":52},{"name":"vae","type":"VAE","link":61}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":34,"type":"Note","pos":{"0":831,"1":501},"size":{"0":282.8617858886719,"1":164.08004760742188},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["Note that Flux dev and schnell do not have any negative prompt so CFG should be set to 1.0. Setting CFG to 1.0 means the negative prompt is ignored."],"color":"#432","bgcolor":"#653"},{"id":42,"type":"VAELoader","pos":{"0":21,"1":56},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[61],"slot_index":0}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.safetensors"]},{"id":40,"type":"UnetLoaderGGUF","pos":{"0":5,"1":238},"size":{"0":315,"1":58},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[58],"slot_index":0}],"properties":{"Node name for S&R":"UnetLoaderGGUF"},"widgets_values":["flux1-dev-Q4_0.gguf"]},{"id":35,"type":"FluxGuidance","pos":{"0":699,"1":36},"size":{"0":211.60000610351562,"1":58},"flags":{},"order":7,"mode":0,"inputs":[{"name":"conditioning","type":"CONDITIONING","link":56}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[57],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"FluxGuidance"},"widgets_values":[3.5]},{"id":31,"type":"KSampler","pos":{"0":827,"1":195},"size":{"0":315,"1":262},"flags":{},"order":8,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":58},{"name":"positive","type":"CONDITIONING","link":57},{"name":"negative","type":"CONDITIONING","link":55},{"name":"latent_image","type":"LATENT","link":51}],"outputs":[{"name":"LATENT","type":"LATENT","links":[52],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[509381428649126,"randomize",20,1,"euler","simple",1]},{"id":41,"type":"DualCLIPLoaderGGUF","pos":{"0":20,"1":381},"size":{"0":315,"1":106},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[59,60],"slot_index":0}],"properties":{"Node name for S&R":"DualCLIPLoaderGGUF"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","clip_l.safetensors","flux"]},{"id":27,"type":"EmptySD3LatentImage","pos":{"0":471,"1":455},"size":{"0":315,"1":106},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[51],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"EmptySD3LatentImage"},"widgets_values":[1344,768,1],"color":"#323","bgcolor":"#535"},{"id":6,"type":"CLIPTextEncode","pos":{"0":359,"1":185},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":59}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[56],"slot_index":0}],"title":"CLIP Text Encode (Positive Prompt)","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["RAW photo, complex ultra detailed PHOTO of an exquisitely beautiful (((blonde android girl))), (((H. R. Giger style:1))), (pristine (black:1.3) mesh with golden highlights) as skin, black and red colors, (((specular highlight))), (subsurface scattering), (((150 mm))), complex textures, (colorful engraved gemstones), (intricate engravings), volumetric light, HDR, ((extremely intricate)), (intricate details), robotic parts, intricate joints, intricate parts, beautiful studio soft light, rim light, vibrant details, anatomically complex, (((biomechanical structures))), cable electric wires, microchip, elegant, beautiful background, octane render, 8k, best quality, masterpiece, illustration, an extremely delicate and beautiful, extremely detailed , (realistic, photo-realistic:1.5), amazing, fine detail, masterpiece, best quality, official art, extremely detailed 8k wallpaper, octane render, incredibly absurdres, robot, extremely high resolution textures, cinematic still, ultrarealistic, dark hazy background, two legs, red tubes and wires,"],"color":"#232","bgcolor":"#353"},{"id":9,"type":"SaveImage","pos":{"0":1375,"1":194},"size":[619.2389605108515,549.2055949018495],"flags":{},"order":10,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]}],"links":[[9,8,0,9,0,"IMAGE"],[51,27,0,31,3,"LATENT"],[52,31,0,8,0,"LATENT"],[55,33,0,31,2,"CONDITIONING"],[56,6,0,35,0,"CONDITIONING"],[57,35,0,31,1,"CONDITIONING"],[58,40,0,31,0,"MODEL"],[59,41,0,6,0,"CLIP"],[60,41,0,33,0,"CLIP"],[61,42,0,8,1,"VAE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6830134553650711,"offset":[455.1805741391472,139.5907764781497]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by city96** [comment] 2024-11-06 00:50
Duplicate of https://github.com/city96/ComfyUI-GGUF/issues/7 - see that issue/thread for possible solutions. Downgrading numpy is probably the easiest one.

**Closed by city96** 2024-11-06 00:50 UTC
