### ISSUE TITLE
BUG: module 'comfy.sd' has no attribute 'load_diffusion_model_state_dict'

### ISSUE THREAD

**Issue by cherryboio** [city96/ComfyUI-GGUF#25] opened 2024-08-16 17:21 UTC
When i try to run it i get this error.

```
Error occurred when executing UnetLoaderGGUF:

module 'comfy.sd' has no attribute 'load_diffusion_model_state_dict'

File "E:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 51, in load_unet
model = comfy.sd.load_diffusion_model_state_dict(
```

**Comment by city96** [comment] 2024-08-16 17:42
Duplicate of #23 - update comfyui as instructed in the readme.

**Closed by city96** 2024-08-16 17:42 UTC
