### ISSUE TITLE
LoRA loading has almost no effect when lowvram is triggered

### ISSUE THREAD

**Issue by Danamir** [city96/ComfyUI-GGUF#33] opened 2024-08-17 10:12 UTC
Comparing the effect of a LoRA between GGUF Q8 and full Dev model, it seems the LoRA has almost no effect on the output, even with no error in the logs.

In the following picture, the left is the original, the right is using https://civitai.com/models/644492/jenna-ortega-lora (at 1.0 str for Q8, and 0.7 for Dev) : 

![grid](https://github.com/user-attachments/assets/95e34eb5-2475-48c0-add8-5f420f0f9329)

Do you have a workflow available to test the LoRA loading with GGUF ?

**Comment by city96** [comment] 2024-08-17 10:18
Okay, this is odd. I can reproduce the diminished results on Q8_0 with my own LoRA, but Q4_0 works perfectly. Could you test if this is the case for you too? I'll have to look into it lol

**Comment by Danamir** [comment] 2024-08-17 10:22
Oh yeah you're right, it's working as intended with Q4 ! I should have tested both. 😅

Q4 with LoRA at 0.7 strength : 

![ComfyUI_flux_00586_](https://github.com/user-attachments/assets/970f19a8-5593-459a-abc1-7a41b4a528e2)

**Comment by 3DeeQu** [comment] 2024-08-17 10:27
My Q8 works great with LORA. This is character's LORA, I didnt notice any distortions or inaccuracies. Maybe there is only one problem, everything looks as CFG is higher than 1, the same with the generation speed, with CFG different from 1, it drops in the same way. The generation speed with LORA is almost 2 times lower than without LORA.

**Comment by city96** [comment] 2024-08-17 10:31
@Danamir 
Wait, are we both running Q8_0 in lowvram mode?

>loaded partially 7844.19951171875 7826.2208251953125 89

I think the part that's in system RAM isn't getting the LoRA applied lol

**Comment by city96** [comment] 2024-08-17 10:33
@3DeeQu The speed drop for CFG other than 1.0 is normal, and the LoRA generation does slow down quite a bit at the moment because the weights are applied at runtime. This will hopefully be optimized in the future.

**Comment by Danamir** [comment] 2024-08-17 10:42
> Wait, are we both running Q8_0 in lowvram mode

I don't have the `--lowvram` command line parameter specified, but I can still see the lowvram loading mode being used automatically in ComfyUI, that may be it !

**Comment by kijai** [comment] 2024-08-17 13:50
Complete opposite experience here, in fact this way of applying the LoRA makes it work properly, as otherwise the standard ComfyUI way of using LoRAs is merging it into the weights, and merging to fp8 causes rounding errors (according to comfyanon himself too) and the effect is extremely weak. Here's a comparison:

![image](https://github.com/user-attachments/assets/f3dfb607-3b28-4d20-8a32-a9abdd853b6f)

**Comment by city96** [comment] 2024-08-17 16:40
Changed the title since the main culprit seems to be lowvram, will have to look at the patching logic to see why this happens.

**Comment by KapperBear** [comment] 2024-08-19 07:15
I have only tried one LoRA so far since I just got started with Flux in general, but I had this issue with Q8 GGUF too. And my card is only a RTX 2060, so it always uses the lowvram mode.

**Comment by slothman3878** [comment] 2024-08-19 20:04
The next patch for comfyui may potentially have a fix for this.

https://github.com/comfyanonymous/ComfyUI/commit/bb222ceddb232aafafa99cd4dec38b3719c29d7d

**Comment by city96** [comment] 2024-08-19 20:07
@slothman3878 Sadly that's only for regular FP8 models, the issue here isn't rounding, it's that lowvram never passes the patches to the custom tensors so the part that is on the CPU is missing the LoRA weights.

**Comment by mwoody450** [comment] 2024-08-25 06:22
I've observed this same issue using a Q5 checkpoint.  It took me forever to figure out what was happening, until I tracked it to batch size: I'm hovering so close to using all VRAM (12GB 4070 TI) that the extra images in the batch were - confirmed via system monitoring - causing it to fill VRAM and drop the loras altogether.

Using the --fast and --lowvram switches (though reproduced it without --fast as well).

**Comment by slothman3878** [comment] 2024-08-26 17:12
@JorgeR81 

https://github.com/city96/ComfyUI-GGUF/issues/36

The increase in generation time is because this is a quantized model. The weights of the loras are applied after the model's weights are dequantized.

**Comment by JorgeR81** [comment] 2024-08-26 17:37
> The increase in generation time is because this is a quantized model. The weights of the loras are applied after the model's weights are dequantized.

Yeah, but in my case, lora performance seems to be improved with GGUF.
https://github.com/city96/ComfyUI-GGUF/issues/64#issuecomment-2307772571

For me, the slower times are mostly with Flux FP8, even with a single lora.
I noticed this when I was comparing the lora effect, between FP8 and the GUFF models.

But, strangely, the XLabs loras seem to be very fast, even with Flux FP8.
I wonder if that's got something to do with the way these loras were made ?
Is it because they were "comfy converted" ?

**Comment by city96** [comment] 2024-08-26 17:43
Comfy has special code for FP8 [here](https://github.com/comfyanonymous/ComfyUI/commit/bb222ceddb232aafafa99cd4dec38b3719c29d7d) to avoid precision issues, it was linked further up the thread by @slothman3878 - this might affect FP8 speed with LoRAs.

I haven't looked into it but I suspect most diffusers LoRAs use the diffusers key mapping, which has separate q/k/v keys while the reference one we use uses one merged qkv key. This is why we technically apply 3 separate patches instead of one for those keys.

**Comment by city96** [comment] 2024-08-28 15:15
Could you retest this on latest? It might be fixed.

**Comment by JorgeR81** [comment] 2024-08-28 16:06
It seems to work.

Here is a comparison, with an image from a lora creator that used the Q8_0 model, and shared its workflow.
( I deleted some redundant custom nodes ).

https://civitai.com/models/685017/christina-applegate?modelVersionId=766681

There are small composition differences despite using the same seed. 
Not sure if that related to this issue.
Maybe there are some differences in the way random noise is handled, on different systems ? 

**civit.ai image** ( from the lora creator )

![flux_00158_](https://github.com/user-attachments/assets/d72ff544-0353-439e-ba79-1f1dc83fb4e0)


**my image:**

![ComfyUI_temp_iguvr_00001_](https://github.com/user-attachments/assets/3bcd3499-5b81-457a-8a8d-0679d7c05f29)

**Comment by city96** [comment] 2024-08-28 18:24
Pushed a fix for it not actually unloading when the LoRA loader is deleted https://github.com/city96/ComfyUI-GGUF/commit/abe5c6a6c90a3f8a53a097614bf749de506c6df7 (spotted by @RandomGitUser321)

**Comment by Danamir** [comment] 2024-08-28 21:35
Yes it seems to be working !

I tested with GGUF dev-Q4_K_S (the only one that was previously working), dev-Q6_K, and dev-Q6_0 . All of those are working now.

NB: the text encoder I use is GGUF t5xxl-Q6_K.

**Comment by KapperBear** [comment] 2024-08-29 07:03
Seems to work, yes! I only ran a quick test with Q4_0 and two different LoRAs (one person, one art style), but those worked fine.

**Comment by city96** [comment] 2024-09-05 04:04
Possible second fix for this live here https://github.com/city96/ComfyUI-GGUF/commit/b46c206dd71eee9318a5f13b51b6f6c23c556d8e

Seems like it had a chance to fry subsequent generations in some scenarios due to weights being applied multiple times.

**Closed** 2024-09-09 11:09 UTC

**Comment by DarkAlchy** [comment] 2024-10-22 03:08
I can't get loras to work with gguf 4_1 or 8_0 (haven't tried anything else) as I get page after page of size mismatch. After I updated comfyui I now receive this error when a lora enters the workflow "AttributeError: 'GGMLTensor' object has no attribute 'tensor_type'".  I am on a 4090 too.
