### ISSUE TITLE
Q8_0, adding multiple lora makes generating very slow

### ISSUE THREAD

**Issue by frankyifei** [city96/ComfyUI-GGUF#113] opened 2024-09-23 17:41 UTC
I have noticed slow down generating if I add more than 1 lora to the workflow, it did not happen to FP8, so I believe there is something wrong in gguf plugin or in comfyui itself that caused this. do you have any idea why is this happening, it even happens to Q5_K_S. 
Test result, Q5_K_S 4.97s/it without any lora, with 2 loras 6.59s/it.  Q8_0 4.30s/it without lora, 5.65s/it with 2 loras.

**Comment by city96** [comment] 2024-09-23 21:21
Duplicate of https://github.com/city96/ComfyUI-GGUF/issues/36 - see explanation and possible ways to speed it up slightly towards the bottom.

**Closed by city96** 2024-09-23 21:21 UTC
